version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test the library
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
