version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Building the library
          command: npm run build

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
